import type { NextPage } from 'next';
import Head from 'next/head';
import { Row, Col, Button, Card, Divider } from "antd";
import WalletConnect from '../components/WalletConnect';
import { useStoreActions, useStoreState } from "../utils/store";
import Link from 'next/link';
import { useState, useEffect } from 'react';
import { getAssets } from "../utils/cardano";
import homepic2 from '../public/images/homepic2.png';
import NftGrid from "../components/NftGrid";
import TextRotator from "../components/TextRotator";
import Image from 'next/image';
import styles from "../styles/Home.module.css";
import initLucid from '../utils/lucid';

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)
  const [nftList, setNftList] = useState([])

  useEffect(() => {
    //const lucid = initLucid(walletStore.name)
    // if (walletStore.address != "") {
    //   getAssets(walletStore.address)
    //     .then((res: any) => { setNftList(res.addressInfo.nfts) })
    // }
  }, [walletStore.address])

  return (
    <div className="px-10">
      <Head>
        <title>Cardano dapp quickstart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <div>
              <span>::</span>
              <Col className='text-center'>
              <Image src={homepic2} alt="DApp360 Home" width="100px" height="100px"/>
              </Col>
              <h1>.</h1>
              <span>.</span>
        </div>
        <section className={styles.main__section}>
          <Row gutter={16}>

            <Col xl={16} lg={16}  md={24} sm={24} xs={24} className={styles.main__section__div}>
              <Row>
                <Col lg={24} xs={24} className={styles.mobile__header}>
                  <Row>
                    <Col lg={24} xs={24}  md={24} className={styles.mobile__header}>
                      <TextRotator
                        words={[
                          <span className={styles.main__section__span2} key={1}>
                            CPass
                            <span className={styles.main__section__span__yellow}>
                              .
                            </span>
                          </span>,
                          <span
                            className={styles.main__section__span2}
                            key={2}
                            style={{ color: "#FFC6C6" }}
                          >
                            Developer DAO
                            <span className={styles.main__section__span__yellow}>
                              .
                            </span>
                          </span>,
                          <span
                            className={styles.main__section__span2}
                            key={3}
                            style={{ color: "#F37038" }}
                          >
                            redefining the future of opensource{" "}
                          </span>,
                          <span
                            className={styles.main__section__span2}
                            key={4}
                            style={{ color: "#E2FFC6" }}
                          >
                            Connect your NFT to enter{" "}
                            <span className={styles.main__section__span__yellow}>
                              .
                            </span>
                          </span>,
                        ]}/>
                    </Col>
                  </Row>
                </Col>

                <Col lg={24} xs={24} className="pt-2 text-center">
                  <p className={styles.main__section__text}>
                  Empowering Haskell and Cardano Developers
                  </p>
                </Col>

                <Col lg={24} xs={24} className="pt-2">
                  {/* <Button
                    size="large"
                    className={styles.main__section__button}
                    onClick={() => {
                      router.push("/our-story");
                    }}>
                    Our Story
                  </Button> */}
                </Col>
              </Row>
            </Col>

            <Col xl={4} lg={4} md={4} sm={4} className={styles.second__pic}>
              {/* <Image src={homepic2} alt="homepic2" /> */}
            </Col>

            <Col xs={24} className={styles.mobileart}>
              {/* <Image src={mart} alt="homepic2" /> */}
            </Col>
          </Row>
        </section>
      </div>

      
        <div className="text-center space-y-4">
          <WalletConnect />
        </div>

      <div className="flex-1">
      </div>
      <div>Address: {walletStore.address}</div>
      <div>Ada Balance: {walletStore.balance}</div>
      <div className="mx-40 my-10">
      <div>Your NFTs:</div>
        <NftGrid nfts={nftList} />
        <Link href="/helios">
          <button className="btn btn-primary m-5" >Smart Contract example</button>
        </Link>
      </div>

    </div>
  )
}

export default Home
