import type { NextPage } from 'next';
import Head from 'next/head';
import { Row, Col, Button, Card, Divider } from "antd";
import WalletConnect from '../components/WalletConnect';
import { useStoreActions, useStoreState } from "../utils/store";
import Link from 'next/link';
import { useState, useEffect } from 'react';
import { getAssets } from "../utils/cardano";
import homepic2 from '../public/images/homepic2.png';
import NftGrid from "../components/NftGrid";
import TextRotator from "../components/TextRotator";
import Image from 'next/image';
import styles from "../styles/Home.module.css";
import initLucid from '../utils/lucid';

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)
  const [nftList, setNftList] = useState([])

  useEffect(() => {
    // const lucid = initLucid(walletStore.name)
    // if (walletStore.address != "") {
    //   getAssets(walletStore.address)
    //     .then((res: any) => { setNftList(res.addressInfo.nfts) })
    // }
  }, [walletStore.address])


  const styles = {
    container: {
      backgroundColor: "#0F1729",
    }
  }

  return (
    <div className="" style={styles.container}>
      <Head>
        <title>CPass Developer DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <div className='mb-4'>
              <Col className='text-center mt-6'>
              <Image src={homepic2} alt="DApp360 Home" width="100px" height="100px"/>
              </Col>
        </div>
        <section>
          <Row gutter={16}>

            <Col xl={16} lg={16}  md={24} sm={24} xs={24}>
              <Row>
                <Col lg={24} xs={24}>
                  <Row>
                    <Col lg={24} xs={24}  className='mt-8'>
                      <TextRotator
                        words={[
                          <span>
                            CPass
                            <span>
                              .
                            </span>
                          </span>,
                          <span style={{ color: "#FFC6C6" }}>
                            Developer DAO
                            <span>
                              .
                            </span>
                          </span>,
                          <span style={{ color: "#F37038" }}>
                            redefining the future of opensource{" "}
                          </span>,
                          <span style={{ color: "#E2FFC6" }}>
                            Connect your NFT to enter{" "}
                            <span>
                              .
                            </span>
                          </span>,
                        ]}/>
                    </Col>
                  </Row>
                </Col>

                <Col lg={24} xs={24} className="pt-2 text-center">
                  <p>
                  Empowering Haskell and Cardano Developers
                  </p>
                </Col>
              </Row>
            </Col>
          </Row>
        </section>
      </div>

      
        <div className="text-center mt-8">
          <WalletConnect />
        </div>

      <div className="alert my-20 alert-success shadow-lg grid grid-cols-12">
        <div className=''>
          <svg xmlns="http://www.w3.org/2000/svg" className="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          <span> Confirm your Address  :  {walletStore.address}</span>
        </div>
      </div>
      
      <div>
      <div>Your NFTs:</div>
        <NftGrid nfts={nftList} />
        <Link href="/helios">
          <button className="btn btn-primary m-5 justify-center" >PROCEED to vote on PROPOSALS</button>
        </Link>
      </div>

    </div>
  )
}

export default Home